### Test root endpoint
GET http://localhost:7007/api/v1

###

### Create Poem
POST http://localhost:7007/api/v1/poem
Content-Type: application/json

{
  "poem": "Autumn leaves drifting, whispers carried on the breeze, time folds into dusk."
}
###

### Get all haikuses
GET http://localhost:7007/api/v1/poem
###

### Get poem by id
GET http://localhost:7007/api/v1/poem/1
###

### Update poem
PUT http://localhost:7007/api/v1/poem/1
Content-Type: application/json

{
  "poem": "I have shat my pants, oops hehe"
}
###

### Delete poem
DELETE http://localhost:7007/api/v1/poem/4
###

### Delete all poems
DELETE http://localhost:7007/api/v1/poem
### or
DELETE http://localhost:7007/api/v1/poem/

